- name: Copy Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/{{item}}
  loop:
    - prometheus.yml
    - record-rules.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for Prometheus Service to Start
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 60